version: '3'

services:
  proxy:
    build:
      dockerfile: $PWD/Dockerfile
      context: .
    image: "docker.pkg.github.com/pilshchikov/ftpproxy:0.1"
    ports:
      - "${PORT}:9000"
    volumes:
      - "${STORAGE_PATH}:/storage"
    entrypoint:
      - "address=${ADDRESS}"
      - "login=${LOGIN}"
      - "password=${PASSWORD}"
      - "storage=/storage"
      - "maxSize=${MAX_SIZE}"
